language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS wordpress;" -uroot; fi
  - composer install

script: vendor/bin/behat